<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Determine Road Bike</name>
  <uuid>a5856f15-8f2c-4ee4-b0a9-3997514eb0ba</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Tire Size' is at least 18 and less than 30
	and Geometry is one of { "sporty", "racey", "aggressive" } 
	and Gearing is at least 18 and less than 27
then
	set decision to "Road Bike" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
