<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Determine Fat Bike</name>
  <uuid>2a0a589b-0390-44d5-9b5e-0de0186fb36c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Tire Size' is at least 50
then
	set decision to "Fat Bike" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
