<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Determine Gravel Bike</name>
  <uuid>598109bf-462a-4473-9eb3-47fd4c368bbb</uuid>
  <documentation><![CDATA[This rule will determine if the bike is a gravel bike.]]></documentation>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Tire Size' is at least 30 and less than 50
	and Geometry is "relaxed"
	and Gearing is at least 9 and less than 13
then
	set decision to "Gravel Bike" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
